name: Build iOS App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install npm dependencies
        run: npm install

      - name: Install CocoaPods
        run: |
          cd ios/CoinMob
          pod install
          cd ../..

      - name: Build iOS app
        run: |
          xcodebuild \
          -workspace ios/CoinMob/CoinMob.xcworkspace \
          -scheme CoinMob \
          -configuration Release \
          -sdk iphoneos

      - name: List build products
        run: ls -R ios/CoinMob/build
