name: Build iOS App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install npm dependencies
        run: npm install

      - name: Show iOS structure
        run: ls -R ios

      - name: Install CocoaPods
        run: |
          cd ios
          pod install
          cd ..

      - name: Build iOS
        run: |
          xcodebuild \
          -workspace ios/CoinMob.xcworkspace \
          -scheme CoinMob \
          -configuration Release \
          -sdk iphoneos
